apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbotservice
spec:
  selector:
    matchLabels:
      app: chatbotservice
  template:
    metadata:
      labels:
        app: chatbotservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 50
      containers:
      - name: server
        image: chatbotservice
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        readinessProbe:
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9090"]
        livenessProbe:
          periodSeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:9090"]
        #- name: RECOMMENDATION_SERVICE_ADDR
        #  value: "recommendationservice:8080"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: chatbotservice
spec:
  type: ClusterIP
  selector:
    app: chatbotservice
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
