{
 "title": "Chatbot Metrics Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Process RAM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "system_usage{resource_type=\"Process_Memory\"}",
     "legendFormat": "MB"
    }
   ]
  },
  {
   "title": "Current Process RAM in MB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_usage{resource_type=\"Process_Memory\"}",
     "legendFormat": "MB"
    }
   ]
  },
  {
   "title": "Peak process RAM in MB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{resource_type=\"Peak_Memory\"}",
     "legendFormat": "MB"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_usage{resource_type=\"CPU\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Current CPU Usage in %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{resource_type=\"CPU\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Average Request Time in seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{resource_type=\"Average Request Time\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Latest Request Time in seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{resource_type=\"Latest Request Time\"}",
     "legendFormat": "seconds"
    }
   ]
  }
 ]
}